// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace QuantConnect.Brokerages.Bitfinex.Rest.Json
{
    public class ErrorResponse
    {
        [JsonProperty("message")]
        public string Message { get; set; }
    }

}
